[versions]
agp = "8.11.1"
firebaseBom = "33.16.0"
junit = "4.13.2"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
koinAndroid = "4.1.0"
kotlin = "2.2.0"
mockk = "1.14.5"
kotlinxCoroutinesAndroid = "1.10.2"

[libraries]
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

